clone:
  depth: full
pipelines:
  branches:
    main:
      - step:
          script:
            - git remote set-url origin ${BITBUCKET_GIT_SSH_ORIGIN}
            - git push --mirror git@github.com:TheJacksonLaboratory/cs-nf-pipelines.git